### ISSUE TITLE
failed to load robot in rviz 

### ISSUE THREAD

**Issue by gezp** [Geekgineer/spcbot#1]
when i run `roslaunch spcbot_description rviz.launch ` ,there is nothing in viewpoint of rviz. Global Status is **Error** and display “For frame [map]: Fixed Frame [map] does not exist”. 

then i set Fixed Frame in Global Options chassis and add Add RobotModel, i see the robot after these config.Maybe you can launch rviz with config file so that not confuse beginners just like me after running your command.

you can change the line in rvize.launch:
`<node pkg="rviz" type="rviz" name="rviz" args="-d $(find spcbot_description) /launch/ spcbot.rviz" >  `

and you  offer  config file **spcbot.rviz**

by the way, you can add a  link "world" just fixed with chassis in urdf, which can be used as world frame in rviz.

**Comment by Geekgineer** [comment]
Thank you for the feedback and your interest.
I add the **spcbot.rviz** with the proper configuration and modify the **rviz lunch** file as you suggested.
also, update the master branch.

![image](https://user-images.githubusercontent.com/16764177/70861954-13de7180-1f3e-11ea-8153-c9701eec7360.png)
